### ISSUE TITLE
`npm run dev` works but prints some errors

### ISSUE THREAD

**Issue by francoismassart** [keithamus/npm-scripts-example#44]
I'm on `node v7.9.0` + `npm 4.2.0` + Mac OS 10.12.6 (Sierra)

Running `npm run dev` works but prints some errors inside my Terminal window

```
npm run dev

> npm-scripts-example@1.0.0 dev /Users/francois/npm-scripts-example
> npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"

[Mon, 05 Mar 2018 14:23:52 GMT] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 0.0.0.0:9090
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at doListen (net.js:1428:7)
    at _combinedTickCallback (internal/process/next_tick.js:83:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)

npm ERR! Darwin 16.7.0
npm ERR! argv "/Users/francois/.nvm/versions/node/v7.9.0/bin/node" "/Users/francois/.nvm/versions/node/v7.9.0/bin/npm" "run" "dev"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! npm-scripts-example@1.0.0 dev: `npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the npm-scripts-example@1.0.0 dev script 'npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the npm-scripts-example package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs npm-scripts-example
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls npm-scripts-example
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/francois/.npm/_logs/2018-03-05T14_23_53_610Z-debug.log
francois@MacBook-Pro-de-Francois-2:~/npm-scripts-example$ live reload server listening on port 9091 reloading on files dist/
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9091
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1263:14)
    at listenInCluster (net.js:1304:12)
    at Server.listen (net.js:1402:7)
    at LiveReloadServer (/Users/francois/npm-scripts-example/node_modules/live-reload/index.js:31:12)
    at Object.<anonymous> (/Users/francois/npm-scripts-example/node_modules/live-reload/bin/reload.js:15:5)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

/Users/francois/npm-scripts-example/node_modules/socket.io/lib/store.js:35
Store.prototype.__proto__ = EventEmitter.prototype;
                                        ^

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/francois/npm-scripts-example/node_modules/socket.io/lib/store.js:35:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/francois/npm-scripts-example/node_modules/socket.io/lib/manager.js:16:13)
    at Module._compile (module.js:571:32)
(node:39868) DeprecationWarning: os.tmpDir() is deprecated. Use os.tmpdir() instead.
[Mon, 05 Mar 2018 14:23:56 GMT] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/604.5.6 (KHTML, like Gecko) Version/11.0.3 Safari/604.5.6"
[Mon, 05 Mar 2018 14:23:56 GMT] "GET /" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36"
  generated dist/main.css.map
  compiled dist/main.css

  rendered dist/index.html
```
Here is the content of `/Users/francois/.npm/_logs/2018-03-05T14_23_53_610Z-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/francois/.nvm/versions/node/v7.9.0/bin/node',
1 verbose cli   '/Users/francois/.nvm/versions/node/v7.9.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'dev' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle npm-scripts-example@1.0.0~predev: npm-scripts-example@1.0.0
6 silly lifecycle npm-scripts-example@1.0.0~predev: no script for predev, continuing
7 info lifecycle npm-scripts-example@1.0.0~dev: npm-scripts-example@1.0.0
8 verbose lifecycle npm-scripts-example@1.0.0~dev: unsafe-perm in lifecycle true
9 verbose lifecycle npm-scripts-example@1.0.0~dev: PATH: /Users/francois/.nvm/versions/node/v7.9.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/francois/npm-scripts-example/node_modules/.bin:/Users/francois/.nvm/versions/node/v7.9.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/git/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/sw/bin:/sw/sbin:/Users/francois/.composer/vendor/bin:/Users/francois/.composer/vendor/bin
10 verbose lifecycle npm-scripts-example@1.0.0~dev: CWD: /Users/francois/npm-scripts-example
11 silly lifecycle npm-scripts-example@1.0.0~dev: Args: [ '-c',
11 silly lifecycle   'npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"' ]
12 silly lifecycle npm-scripts-example@1.0.0~dev: Returned: code: 1  signal: null
13 info lifecycle npm-scripts-example@1.0.0~dev: Failed to exec dev script
14 verbose stack Error: npm-scripts-example@1.0.0 dev: `npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/francois/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/francois/.nvm/versions/node/v7.9.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid npm-scripts-example@1.0.0
16 verbose cwd /Users/francois/npm-scripts-example
17 error Darwin 16.7.0
18 error argv "/Users/francois/.nvm/versions/node/v7.9.0/bin/node" "/Users/francois/.nvm/versions/node/v7.9.0/bin/npm" "run" "dev"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error npm-scripts-example@1.0.0 dev: `npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"`
23 error Exit status 1
24 error Failed at the npm-scripts-example@1.0.0 dev script 'npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the npm-scripts-example package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     npm run open:dev -s && parallelshell "npm run live-reload -s" "npm run serve -s" "npm run watch -s"
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs npm-scripts-example
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls npm-scripts-example
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by francoismassart** [comment]
Looks like the errors were due to an incompatibility between the old `karma-phantomjs-launcher` version and Mac OS Sierra... 

Fixed via https://github.com/keithamus/npm-scripts-example/commit/41d20065b9fc986a0f737002adfb19880f681595
